*&---------------------------------------------------------------------*
*& Include          YCL115_002_TOP
*&---------------------------------------------------------------------*
TABLES: SCARR.        "화면에있는 인풋필드의 값을 가져오기위해서 선언하는것.(구조체 변수)


DATA: OK_CODE TYPE SY-UCOMM,
      SAVE_OK TYPE SY-UCOMM.

DATA: GT_SCARR TYPE TABLE OF SCARR.         "인터널테이블 선언

SELECTION-SCREEN BEGIN OF SCREEN 0101 AS SUBSCREEN.     "서브스크린
SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-T01.

SELECTION-SCREEN BEGIN OF LINE.       "BEGIN OF LINE을 하게되면 TEXT가 없어진다.(직접 COMMENT를 달아주어야함)
SELECTION-SCREEN COMMENT 1(10) TEXT-L02 FOR FIELD S_CARRID.   "항공사ID
SELECT-OPTIONS: S_CARRID FOR SCARR-CARRID.
                 "생성위치는 생략이가능하다.(첫번째 자리나 들어갈수있는위치에서 가장 왼쪽에 알아서 만들어짐)
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(10) TEXT-L03 FOR FIELD S_CARRNM. " 항공사명
SELECT-OPTIONS S_CARRNM FOR SCARR-CARRNAME.
SELECTION-SCREEN PUSHBUTTON 77(10) TEXT-L01 USER-COMMAND SEARCH.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B01.
SELECTION-SCREEN END OF SCREEN 0101.
