*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVSA15VEN.......................................*
FORM GET_DATA_ZVSA15VEN.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTSA15VEN WHERE
(VIM_WHERETAB) .
    CLEAR ZVSA15VEN .
ZVSA15VEN-MANDT =
ZTSA15VEN-MANDT .
ZVSA15VEN-LIFNR =
ZTSA15VEN-LIFNR .
ZVSA15VEN-LAND1 =
ZTSA15VEN-LAND1 .
ZVSA15VEN-CARRID =
ZTSA15VEN-CARRID .
ZVSA15VEN-NAME1 =
ZTSA15VEN-NAME1 .
ZVSA15VEN-NAME2 =
ZTSA15VEN-NAME2 .
ZVSA15VEN-VENCA =
ZTSA15VEN-VENCA .
ZVSA15VEN-MEALNO =
ZTSA15VEN-MEALNO .
ZVSA15VEN-PRICE =
ZTSA15VEN-PRICE .
ZVSA15VEN-WAERS =
ZTSA15VEN-WAERS .
<VIM_TOTAL_STRUC> = ZVSA15VEN.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVSA15VEN .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVSA15VEN.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVSA15VEN-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTSA15VEN WHERE
  LIFNR = ZVSA15VEN-LIFNR AND
  LAND1 = ZVSA15VEN-LAND1 AND
  CARRID = ZVSA15VEN-CARRID .
    IF SY-SUBRC = 0.
    DELETE ZTSA15VEN .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTSA15VEN WHERE
  LIFNR = ZVSA15VEN-LIFNR AND
  LAND1 = ZVSA15VEN-LAND1 AND
  CARRID = ZVSA15VEN-CARRID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTSA15VEN.
    ENDIF.
ZTSA15VEN-MANDT =
ZVSA15VEN-MANDT .
ZTSA15VEN-LIFNR =
ZVSA15VEN-LIFNR .
ZTSA15VEN-LAND1 =
ZVSA15VEN-LAND1 .
ZTSA15VEN-CARRID =
ZVSA15VEN-CARRID .
ZTSA15VEN-NAME1 =
ZVSA15VEN-NAME1 .
ZTSA15VEN-NAME2 =
ZVSA15VEN-NAME2 .
ZTSA15VEN-VENCA =
ZVSA15VEN-VENCA .
ZTSA15VEN-MEALNO =
ZVSA15VEN-MEALNO .
ZTSA15VEN-PRICE =
ZVSA15VEN-PRICE .
ZTSA15VEN-WAERS =
ZVSA15VEN-WAERS .
    IF SY-SUBRC = 0.
    UPDATE ZTSA15VEN ##WARN_OK.
    ELSE.
    INSERT ZTSA15VEN .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVSA15VEN-UPD_FLAG,
STATUS_ZVSA15VEN-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZVSA15VEN.
  SELECT SINGLE * FROM ZTSA15VEN WHERE
LIFNR = ZVSA15VEN-LIFNR AND
LAND1 = ZVSA15VEN-LAND1 AND
CARRID = ZVSA15VEN-CARRID .
ZVSA15VEN-MANDT =
ZTSA15VEN-MANDT .
ZVSA15VEN-LIFNR =
ZTSA15VEN-LIFNR .
ZVSA15VEN-LAND1 =
ZTSA15VEN-LAND1 .
ZVSA15VEN-CARRID =
ZTSA15VEN-CARRID .
ZVSA15VEN-NAME1 =
ZTSA15VEN-NAME1 .
ZVSA15VEN-NAME2 =
ZTSA15VEN-NAME2 .
ZVSA15VEN-VENCA =
ZTSA15VEN-VENCA .
ZVSA15VEN-MEALNO =
ZTSA15VEN-MEALNO .
ZVSA15VEN-PRICE =
ZTSA15VEN-PRICE .
ZVSA15VEN-WAERS =
ZTSA15VEN-WAERS .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVSA15VEN USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVSA15VEN-LIFNR TO
ZTSA15VEN-LIFNR .
MOVE ZVSA15VEN-LAND1 TO
ZTSA15VEN-LAND1 .
MOVE ZVSA15VEN-CARRID TO
ZTSA15VEN-CARRID .
MOVE ZVSA15VEN-MANDT TO
ZTSA15VEN-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTSA15VEN'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTSA15VEN TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTSA15VEN'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
